// Generated by gencpp from file rbe3002_turtle06/FrontierMsg.msg
// DO NOT EDIT!


#ifndef RBE3002_TURTLE06_MESSAGE_FRONTIERMSG_H
#define RBE3002_TURTLE06_MESSAGE_FRONTIERMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace rbe3002_turtle06
{
template <class ContainerAllocator>
struct FrontierMsg_
{
  typedef FrontierMsg_<ContainerAllocator> Type;

  FrontierMsg_()
    : header()
    , centroid()
    , cell_positions()  {
    }
  FrontierMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , centroid(_alloc)
    , cell_positions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _centroid_type;
  _centroid_type centroid;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _cell_positions_type;
  _cell_positions_type cell_positions;





  typedef boost::shared_ptr< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> const> ConstPtr;

}; // struct FrontierMsg_

typedef ::rbe3002_turtle06::FrontierMsg_<std::allocator<void> > FrontierMsg;

typedef boost::shared_ptr< ::rbe3002_turtle06::FrontierMsg > FrontierMsgPtr;
typedef boost::shared_ptr< ::rbe3002_turtle06::FrontierMsg const> FrontierMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rbe3002_turtle06

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rbe3002_turtle06': ['/home/wpirbe/catkin_ws/src/rbe3002_turtle06/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4134cb203df22c66dd1dc71eb3cd5c11";
  }

  static const char* value(const ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4134cb203df22c66ULL;
  static const uint64_t static_value2 = 0xdd1dc71eb3cd5c11ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbe3002_turtle06/FrontierMsg";
  }

  static const char* value(const ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Point centroid\n\
geometry_msgs/Point[] cell_positions\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.centroid);
      stream.next(m.cell_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FrontierMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "centroid: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.centroid);
    s << indent << "cell_positions[]" << std::endl;
    for (size_t i = 0; i < v.cell_positions.size(); ++i)
    {
      s << indent << "  cell_positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.cell_positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBE3002_TURTLE06_MESSAGE_FRONTIERMSG_H
