// Generated by gencpp from file rbe3002_turtle06/GetFrontiersResponse.msg
// DO NOT EDIT!


#ifndef RBE3002_TURTLE06_MESSAGE_GETFRONTIERSRESPONSE_H
#define RBE3002_TURTLE06_MESSAGE_GETFRONTIERSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rbe3002_turtle06/FrontierMsg.h>

namespace rbe3002_turtle06
{
template <class ContainerAllocator>
struct GetFrontiersResponse_
{
  typedef GetFrontiersResponse_<ContainerAllocator> Type;

  GetFrontiersResponse_()
    : frontier_cells()  {
    }
  GetFrontiersResponse_(const ContainerAllocator& _alloc)
    : frontier_cells(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >::other >  _frontier_cells_type;
  _frontier_cells_type frontier_cells;





  typedef boost::shared_ptr< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFrontiersResponse_

typedef ::rbe3002_turtle06::GetFrontiersResponse_<std::allocator<void> > GetFrontiersResponse;

typedef boost::shared_ptr< ::rbe3002_turtle06::GetFrontiersResponse > GetFrontiersResponsePtr;
typedef boost::shared_ptr< ::rbe3002_turtle06::GetFrontiersResponse const> GetFrontiersResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rbe3002_turtle06

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rbe3002_turtle06': ['/home/wpirbe/catkin_ws/src/rbe3002_turtle06/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6129dd59a1e4fe58cd44208589e088ed";
  }

  static const char* value(const ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6129dd59a1e4fe58ULL;
  static const uint64_t static_value2 = 0xcd44208589e088edULL;
};

template<class ContainerAllocator>
struct DataType< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbe3002_turtle06/GetFrontiersResponse";
  }

  static const char* value(const ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
FrontierMsg[] frontier_cells\n\
\n\
================================================================================\n\
MSG: rbe3002_turtle06/FrontierMsg\n\
Header header\n\
geometry_msgs/Point centroid\n\
geometry_msgs/Point[] cell_positions\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frontier_cells);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFrontiersResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbe3002_turtle06::GetFrontiersResponse_<ContainerAllocator>& v)
  {
    s << indent << "frontier_cells[]" << std::endl;
    for (size_t i = 0; i < v.frontier_cells.size(); ++i)
    {
      s << indent << "  frontier_cells[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rbe3002_turtle06::FrontierMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.frontier_cells[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBE3002_TURTLE06_MESSAGE_GETFRONTIERSRESPONSE_H
