// Generated by gencpp from file rbe3002_turtle06/GetFrontiers.msg
// DO NOT EDIT!


#ifndef RBE3002_TURTLE06_MESSAGE_GETFRONTIERS_H
#define RBE3002_TURTLE06_MESSAGE_GETFRONTIERS_H

#include <ros/service_traits.h>


#include <rbe3002_turtle06/GetFrontiersRequest.h>
#include <rbe3002_turtle06/GetFrontiersResponse.h>


namespace rbe3002_turtle06
{

struct GetFrontiers
{

typedef GetFrontiersRequest Request;
typedef GetFrontiersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFrontiers
} // namespace rbe3002_turtle06


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbe3002_turtle06::GetFrontiers > {
  static const char* value()
  {
    return "6129dd59a1e4fe58cd44208589e088ed";
  }

  static const char* value(const ::rbe3002_turtle06::GetFrontiers&) { return value(); }
};

template<>
struct DataType< ::rbe3002_turtle06::GetFrontiers > {
  static const char* value()
  {
    return "rbe3002_turtle06/GetFrontiers";
  }

  static const char* value(const ::rbe3002_turtle06::GetFrontiers&) { return value(); }
};


// service_traits::MD5Sum< ::rbe3002_turtle06::GetFrontiersRequest> should match 
// service_traits::MD5Sum< ::rbe3002_turtle06::GetFrontiers > 
template<>
struct MD5Sum< ::rbe3002_turtle06::GetFrontiersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbe3002_turtle06::GetFrontiers >::value();
  }
  static const char* value(const ::rbe3002_turtle06::GetFrontiersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbe3002_turtle06::GetFrontiersRequest> should match 
// service_traits::DataType< ::rbe3002_turtle06::GetFrontiers > 
template<>
struct DataType< ::rbe3002_turtle06::GetFrontiersRequest>
{
  static const char* value()
  {
    return DataType< ::rbe3002_turtle06::GetFrontiers >::value();
  }
  static const char* value(const ::rbe3002_turtle06::GetFrontiersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbe3002_turtle06::GetFrontiersResponse> should match 
// service_traits::MD5Sum< ::rbe3002_turtle06::GetFrontiers > 
template<>
struct MD5Sum< ::rbe3002_turtle06::GetFrontiersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbe3002_turtle06::GetFrontiers >::value();
  }
  static const char* value(const ::rbe3002_turtle06::GetFrontiersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbe3002_turtle06::GetFrontiersResponse> should match 
// service_traits::DataType< ::rbe3002_turtle06::GetFrontiers > 
template<>
struct DataType< ::rbe3002_turtle06::GetFrontiersResponse>
{
  static const char* value()
  {
    return DataType< ::rbe3002_turtle06::GetFrontiers >::value();
  }
  static const char* value(const ::rbe3002_turtle06::GetFrontiersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBE3002_TURTLE06_MESSAGE_GETFRONTIERS_H
