// Generated by gencpp from file rbe3002_turtle06/GetFrontiersRequest.msg
// DO NOT EDIT!


#ifndef RBE3002_TURTLE06_MESSAGE_GETFRONTIERSREQUEST_H
#define RBE3002_TURTLE06_MESSAGE_GETFRONTIERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbe3002_turtle06
{
template <class ContainerAllocator>
struct GetFrontiersRequest_
{
  typedef GetFrontiersRequest_<ContainerAllocator> Type;

  GetFrontiersRequest_()
    {
    }
  GetFrontiersRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetFrontiersRequest_

typedef ::rbe3002_turtle06::GetFrontiersRequest_<std::allocator<void> > GetFrontiersRequest;

typedef boost::shared_ptr< ::rbe3002_turtle06::GetFrontiersRequest > GetFrontiersRequestPtr;
typedef boost::shared_ptr< ::rbe3002_turtle06::GetFrontiersRequest const> GetFrontiersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rbe3002_turtle06

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rbe3002_turtle06': ['/home/wpirbe/catkin_ws/src/rbe3002_turtle06/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbe3002_turtle06/GetFrontiersRequest";
  }

  static const char* value(const ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFrontiersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rbe3002_turtle06::GetFrontiersRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RBE3002_TURTLE06_MESSAGE_GETFRONTIERSREQUEST_H
